
name: Sync Images to sm.ms

on:
  push:
    paths:
      - '**.png'
      - '**.jpg'
      - '**.jpeg'
      - '**.gif'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests
      env:
        SMMS_API_TOKEN: ${{ secrets.SMMS_API_TOKEN }}

    - name: Upload images to sm.ms
      run: |
        for file in $(find . -type f \( -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.gif" \)); do
          response=$(curl -s -H "Authorization: $SMMS_API_TOKEN" -F "smfile=@$file" https://sm.ms/api/v2/)
          url=$(echo $response | jq -r '.data.url')
          echo "Uploaded $file to $url"
        done
      env:
        SMMS_API_TOKEN: ${{ secrets.SMMS_API_TOKEN }}
